<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateScrequestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('screquests', function (Blueprint $table) {
            $table->increments('id');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->string('status', 255)->nullable();
            $table->string('subject', 255)->nullable();
            $table->string('supportRep', 255)->nullable();
            $table->string('contact', 255)->nullable();
            $table->integer('statusID')->nullable();
            $table->integer('requestID')->nullable();
            $table->dateTime('created_in_system')->nullable();
            $table->string('servicenowID', 255)->nullable();
            $table->dateTime('updated_in_system')->nullable();
            $table->integer('push_to_servicenow')->nullable();

            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('screquests');
    }
}
