<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateScrequestInfosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('screquest_infos', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('requestID')->nullable();
            $table->text('description')->nullable();
            $table->string('priority', 255)->nullable();
            $table->string('status', 255)->nullable();
            $table->text('category')->nullable();
            $table->string('createdBy', 255)->nullable();
            $table->text('subject')->nullable();
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->integer('screquest_id')->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_bin';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('screquest_infos');
    }
}
